name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 45
    name: Test if cached taskfile works
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: "next-9"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm deps
        run: pnpm install

      - name: Print
        id: version
        run: echo "VERSION=$(pnpm task --silent print || true)" >> "$GITHUB_OUTPUT"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
